### ISSUE TITLE
Autowhitelister Problem

### ISSUE THREAD

**Issue by SatelliteRadio** [3dsboy08/Synapse-Issues#12]
Satellite Radio#1653

Autowhitelister

Autowhitelister spits out unknown error whenever I try to auth myself, ive tried ALL of the troubleshooting that mods/admins/members and buyers have suggested. All antivirus have been turned off, including firewall and windows defender, x86 redist installed and reinstalled, deleted synapse folders out of appdata, I even ran this on a fresh fucking VM with nothing but win10 x64 bit and synapse and to no avail, its still fucking broken. ive reinstalled it from scratch 5 times. I have 2fa enabled and when I try to !getsecretkey from the bot I get image 2

![image](https://user-images.githubusercontent.com/31788926/30246461-bb2ed7c4-95af-11e7-97c2-924d589d5b1d.png)

![image](https://user-images.githubusercontent.com/31788926/30246490-67585a52-95b0-11e7-8bff-232fec9d83c2.png)

**Comment by ReidTJ** [comment]
It looks like you aren't a Synapse Buyer looking at the discord image.

**Comment by 3dsboy08** [comment]
This is caused by the request to the Synapse servers failing. Check your firewall, as that is probably the main cause of the issue.

**Comment by ehsaan555** [comment]
Try getting your secretkey now! 
I got eiecctro to re-role you
