### ISSUE TITLE
Synapse wont execute scripts.

### ISSUE THREAD

**Issue by garrows69** [3dsboy08/Synapse-Issues#14]
After I execute Dex synapse wont execute anything, not even print()

**Comment by ehsaan555** [comment]
Try closing your browser - it happened to me once, and I closed my browser and it worked.

**Comment by 3dsboy08** [comment]
Can't reproduce.

If anyone else has the issue, contact me.

**Comment by garrows69** [comment]
I am using this version of Dex.
[DexExplorer.txt](https://github.com/3dsboy08/Synapse-Issues/files/1309496/DexExplorer.txt)
After I execute and it loads I cant execute anything from Synapse. I try print() and warn(). No output
