### ISSUE TITLE
Synapse files not opening

### ISSUE THREAD

**Issue by shtrd** [3dsboy08/Synapse-Issues#15]
shtrd#3867
Synapse+Synapse Autowhitelister not opening at all

This has happened to me since a few days already, synapse and the autowhitelister won't open. I already deleted Raindrop and RaindropV2, same with SynapseAuth and SynapseData from Roaming. I looked at the tutorials in the discord and went through them all, however, it still won't work.
https://i.imgur.com/lwlx0K5.png
https://i.imgur.com/3XrRtze.png
I also have downloaded Visual Studio 2015 and yet, nothing.

**Comment by ehsaan555** [comment]
@shtrd FlatUI.dll is probably missing, disable Windows Defender https://www.youtube.com/watch?v=7bqjm9gjNLM&feature=youtu.be

And you can uninstall Visual Studio it's not needed.
But install this: https://www.microsoft.com/en-gb/download/details.aspx?id=48145

It's not Visual Studio, but it's needed for Synapse for work.
