### ISSUE TITLE
Whitelist wont work

### ISSUE THREAD

**Issue by smithandree** [3dsboy08/Synapse-Issues#16]
I open synapse and it wont whitelist me I went through the whitelister my defender is off aswell.

**Comment by txttext** [comment]
I told him the %appdata% fix but it doesn't work.

**Comment by ehsaan555** [comment]
Try this:
[https://www.youtube.com/watch?v=7bqjm9gjNLM&feature=youtu.be](url)
Otherwise I don't know

**Comment by 3dsboy08** [comment]
Zero information given. Please repost the issue with actual info I can use to help you.
