### ISSUE TITLE
Roblox Window closes when I press attach

### ISSUE THREAD

**Issue by Discord-Baby** [3dsboy08/Synapse-Issues#19]
Hi, just as the title says, the roblox window closes when I press attach. I got a new whitelist key, I deleted the Synapse files and tried to reinstall them; this did nothing. I checked in my %appdata% folder and some of my Synapse files aren't there. 

Thanks

Baby

**Comment by ehsaan555** [comment]
Just re-open ROBLOX and try Attach again, it should work fine.

**Comment by ehsaan555** [comment]
If it doesn't, delete all synapse files and re-download it

**Comment by 3dsboy08** [comment]
Can't reproduce.
