### ISSUE TITLE
Synapse Graphical Error (Flickering)

### ISSUE THREAD

**Issue by BinaraKing** [3dsboy08/Synapse-Issues#21]
Discord Id: **Binara#5278 (206471147368349697)**

Report Type (script issue/etc): **Graphical Issue** (Similar to Discord Electron Issues)

**Report Content:** 
The scripts tab, which displays your preset scripts, tend to flicker every couple of seconds or so. It's similar to discord electron issues, with role colour flickering. Sometimes, the names of the scripts will disappear, and reappear very quickly thus causing a flickering effect.

Images/other details:
[Image #1](https://gyazo.com/5a87ad80efda8ba8c9034f93e0d8dd97)
[Image #2](https://gyazo.com/10b1b97ab393b50315c5a4962c2c72a4)

This could be caused locally(computer issues), due to a possible lack of the required software.

**Comment by 3dsboy08** [comment]
This seems like an issue with the .NET framework listbox itself, cant really fix.

**Comment by ehsaan555** [comment]
Also, I once clicked Attach, then it attached, and when it said "Synapse is ready! Have fun!" I clicked ROcky2u and the Synapse is ready message was halfway up, then I clicked Rocky2u and it just started flickering e.e

**Comment by BinaraKing** [comment]
Solved in Synapse Version 3.2.0 👍
