### ISSUE TITLE
Synapse UI doesn't open suddenly

### ISSUE THREAD

**Issue by ehsaan555** [3dsboy08/Synapse-Issues#22]
Discord Id: 260361379477716992
Report Type (script issue/etc): Synapse.exe
Report Content: Basically, I was on the Synapse Discord Server and someone said "Synapse won't open, is this happening to everyone else?" and everyone replied Nope. Then today my friend said his wouldn't open either. That's two people I've seen say that today.

Images/other details: Their Anti-Viruses were off.

**Comment by 3dsboy08** [comment]
Old issue.
