### ISSUE TITLE
dll test failed

### ISSUE THREAD

**Issue by Shinokima** [3dsboy08/Synapse-Issues#23]
I drop my .synkey file and shows this
                                                                                                                                                                             ![2017-10-15](https://user-images.githubusercontent.com/32809911/31582661-cb5fce6e-b13e-11e7-9b0a-8f91b4fc01ef.png)
                             
idk if the picture is showing tho
I download the thing (visual c++) 
did I download the wrong thing or do I have a problem?

**Comment by Shinokima** [comment]
when I open it and download it says there is another version already

**Comment by Shinokima** [comment]
I reinstalled everything still doesn't work

**Comment by Shinokima** [comment]
3ds just please solve this issue

**Comment by RealCG** [comment]
OP is spamming this issue a bit, but I second this. I have the exact same issue, reinstalling the 2015 C++ runtime does not work. Maybe you have a try/catch block that's catching an error that has nothing to do with the installation of the VS2015 redist, 3ds.

**Comment by ehsaan555** [comment]
Get this homies
https://www.microsoft.com/en-gb/download/details.aspx?id=48145
