### ISSUE TITLE
Waiting for whitelist (did all fixes)

### ISSUE THREAD

**Issue by Chrisstewy111** [3dsboy08/Synapse-Issues#24]
Discord: AbusiveTattleTail#1593

I did everything it said to on the discord errors still not working.

**Comment by KaoticZoom** [comment]
bump!

**Comment by Chrisstewy111** [comment]
bump again....

**Comment by Anonynmousy** [comment]
Dude I payed good money for this and I have Windows 10 -64 bit and I need a fix;( really I want to use it.

**Comment by 3dsboy08** [comment]
Not enough details.
