### ISSUE TITLE
Stuck On Waiting For Whitelist Response

### ISSUE THREAD

**Issue by KaoticZoom** [3dsboy08/Synapse-Issues#25]
Discord Id (ex: 3dsboy08#8037): Kaotic#8904
Report Type (script issue/etc): Waiting For Whitelist Response
Report Content: I did everything it said in the #Downloads channel. I have the 1703 Windows update
Images/other details: [![Screenshot from Gyazo](https://gyazo.com/eb88934310433a17480cb419b9de2437/raw)](https://gyazo.com/eb88934310433a17480cb419b9de2437)

**Comment by Chrisstewy111** [comment]
Same

**Comment by 3dsboy08** [comment]
#errors-info
