### ISSUE TITLE
Stuck on  Waiting For Whitelist Response/Downloading Data

### ISSUE THREAD

**Issue by theclout** [3dsboy08/Synapse-Issues#26]
Discord Id: ramsey#2009
Report Type (script issue/etc): Waiting For Whitelist Response/ Downloading Data
Report Content: I did everything it said in the #Downloads channel. It works on and off but barely at all.
Images/other details: https://gyazo.com/eb88934310433a17480cb419b9de2437

**Comment by Chrisstewy111** [comment]
Same thats why I posted something still haven't got a response ;(
