### ISSUE TITLE
New Synapse Gui/Functions v3.1.9

### ISSUE THREAD

**Issue by djfruitsnacks** [3dsboy08/Synapse-Issues#29]
Discord Id: djfruitsnacks#7313
Report Type (script issue/etc)/Report Content: 

1. Most important, Closes Synapse v3.1.9 after 1 min of opening it without/doing things with it.
2. Somewhat important, Doesnt show being whitelisted.
3. Least important, The new gui is very big on my screen. +when i put in text it doesnt fill up the whole space anyways.

Images/other details:
Sorry im not to sure about that third one, im saying sorry for not being able to show a video of whats going on

![ttrr](https://user-images.githubusercontent.com/33267893/32251920-1ef3fb52-be61-11e7-8214-505c22e58acb.PNG)

**Comment by 3dsboy08** [comment]
First Issue: No idea why that happens. Can't reproduce.
Second Issue: Doesn't need to.
Third Issue: Its an issue with accessibility settings. (your PC)
