### ISSUE TITLE
Synapse no work

### ISSUE THREAD

**Issue by xFunnieuss** [3dsboy08/Synapse-Issues#30]
hello 3dsboi23 synapse has not worked ever since you updated to 3.1.9 and it is probs synapse's fault or something so please fix it 5dsboy927

**Comment by xFunnieuss** [comment]
bro now the issue is theres no DARN SCRIPT TAB.

**Comment by djfruitsnacks** [comment]
This is the format for Synapse issues:

Synapse Issue Format

Discord Id (ex: 3dsboy08#8037):
Report Type (script issue/etc):
Report Content:
Images/other details:

**Comment by ehsaan555** [comment]
yes he added it back. DARNIT

**Comment by JackDragonBuster** [comment]
when i try to open up synapse it says"boot failure (c)"
please help.
