### ISSUE TITLE
Whitelist Error

### ISSUE THREAD

**Issue by Nitility** [3dsboy08/Synapse-Issues#32]
Discord: aII_buII#1348

Issue: I keep on getting an error whenever I try to drag the whitelist file onto the SynapseAuthenticationProcess.

Issue type: Whitelist Error

Image: 
<img width="369" alt="capture2" src="https://user-images.githubusercontent.com/30520290/32401850-0d4322ea-c0d5-11e7-8d47-7f34715817e0.PNG">

**Comment by ehsaan555** [comment]
you dont need to cover that number, its your discord id....
anyway you're probably having some compatibility issues

**Comment by Nitility** [comment]
Thanks for the suggestion, I will try it on my other computer and see if that makes a difference.
