### ISSUE TITLE
Synapse Whitelist not working.

### ISSUE THREAD

**Issue by Nitility** [3dsboy08/Synapse-Issues#34]
Discord: aII_buII#1348

Report type: Whitelist Error

Description: Whenever I use my whitelist provided by the bot when I bought synapse I get an error saying that the key is invalid and it might have already been used. Am I able to receive a new key? And just to let you know, I did not share the whitelist with anyone. The only possibility saying that its been already used is when I used it on my other computer. I have also recently reset my current PC that I use for gaming and using synapse.

Image: 
![synapse_error](https://user-images.githubusercontent.com/30520290/32682254-6f715376-c628-11e7-8114-a9e641514b4a.PNG)

**Comment by Nitility** [comment]
For some reason, I was kicked from the discord server and I believe I was suspected of sharing my key with someone else. I have never shared my key with someone else. I only used the key on two computers and reset my current one a couple of times. I would please like an explanation.

**Comment by Nitility** [comment]
Also, I have been accused of something I have not done and would like to speak with someone. There is also no proof that I shared the key with anyone.

**Comment by 3dsboy08** [comment]
no the server was banned lol

**Comment by Nitility** [comment]
Rip cringe
