### ISSUE TITLE
Attach Error with Synapse (Crashing on Attach : Possible XP Call error)

### ISSUE THREAD

**Issue by BinaraKing** [3dsboy08/Synapse-Issues#38]
Discord Id: **Binara#5278** or **206471147368349697**

Report Type: Error with Launcher Attaching

Report Content:
An issue that has been recurring for some time now after **Synapse's major update** to include full Lua execution. When attempting to join certain games, whenever you attach with Synapse, it will, 99% of the time will crash. An attempt to fix XP Call was made, however was highly ineffective and didn't work. The games that Synapse **typically crashes** on now is: CB:RO, Phantom Forces, etc.

Images/other details:
Many Synapse buyer (including myself), have been experiencing very frequent crashing upon attach. The issue occurs on both Wrapper mode, as well as Full execution mode. When checking task manager, it appears as if ROBLOX is having **memory leaks** after attaching, and crashing.

**Comment by chebureki** [comment]
Anime is gay

**Comment by BinaraKing** [comment]
This has been fixed in the most recent Synapse update 4.1.2 and 4.1.2b.

**Comment by carter-crypto** [comment]
still crashing 4 me
