### ISSUE TITLE
Failed to lock VRAM

### ISSUE THREAD

**Issue by Unet-01** [3dsboy08/Synapse-Issues#4]
Discord: Unit-01#3991
Type: Synapse Issue
Ever since I first got synapse I have had this problem (3dsboy you fuckin know this and you refuse to fix it because you "dont have the issue") After using a script that constantly updates parameters of the script(aka basically every script ever) for a few minutes my console says it failed to lock 500kb-2mb of vram, while my stats clearly say that i am using a whopping 0 TOTAL VRAM as you will see. And i fucking swear if you say its because i have a shitty pc while every one of my stats are above maximum, you can fuck off and play your shitty lego game while jacking off at all the bacon haired trash.

Pic: [![Screenshot from Gyazo](https://gyazo.com/157ee65b97529efa9763cd68479111e3/raw)](https://gyazo.com/157ee65b97529efa9763cd68479111e3)

**Comment by 3dsboy08** [comment]
As I have said 1000 times already, I (or anyone else other then you) was never able to reproduce this bug. If anyone else could reproduce it, it would be nice.

**Comment by 3dsboy08** [comment]
Will be keeping open for 24 hours to see if anyone else has this issue. If not, the issue will be closed.

**Comment by ehsaan555** [comment]
@Unet-01 No one else seems to have the problem, so it's pretty simple when 3ds says he doesn't have it, he doesn't have it.
