### ISSUE TITLE
Debugger program detected?

### ISSUE THREAD

**Issue by Racco0n** [3dsboy08/Synapse-Issues#42]
Not sure if this is related to synapse, but it happened when I was watching youtube.

[https://i.gyazo.com/43cd1feb85203ce0aa0e5a319e94b65d.jpg](Image)

**Comment by Racco0n** [comment]
ffs the image thing didn't work: https://i.gyazo.com/43cd1feb85203ce0aa0e5a319e94b65d.jpg

**Comment by 3dsboy08** [comment]
Probably not Synapse. Check your PC for malware.

**Comment by Racco0n** [comment]
Okay good to know, thanks I'll run malwarebytes again ;3;
