### ISSUE TITLE
teleportservice notfunctioning

### ISSUE THREAD

**Issue by bgamboe** [3dsboy08/Synapse-Issues#49]
**Issue Name:**  teleportservice not fully functional

**Issue Description:**  teleportservice crashes RobloxPlayerBeta.exe

**Describe how to fully reproduce the issue:**  launch a script that uses teleport service (the one i used was server-sided admin by bluntboomer#1259) and That's it

**Other Details:**  I do not know if this a real issue or a compatibility issue with synapse it works with other executors and you can contact me at bgamboe#4052 and ill screenshare exactly what i did

**Comment by 3dsboy08** [comment]
more of general teleport issues, working on it

**Comment by 3dsboy08** [comment]
Fixed in update about to be released.
