### ISSUE TITLE
Whitelist key invalid

### ISSUE THREAD

**Issue by applesos** [3dsboy08/Synapse-Issues#5]
**Discord Id** (ex: apple sauce in your mom#5759):
**Report Type** (Synapse Autowhitelister):
**Report Content:** I've disabled all of my anti-viruses, deleted Synapse/Raindrop folders from %appdata% and restarted by 64-bit PC; yet when i drag my "secret.synkey" into the autowhitelister, It says "[*] A Secret Key has been detected. Please wait...ERROR!"
**Images/other details:**

**Comment by 3dsboy08** [comment]
Invalid bug report.

**Comment by applesos** [comment]
just liek my whitelist key ;-;

**Comment by applesos** [comment]
Also how is it invalid? Just want to know so i can avoid making another invalid bug report.
