### ISSUE TITLE
Crash when inject.

### ISSUE THREAD

**Issue by Hmm465GamingYT** [3dsboy08/Synapse-Issues#52]
Issue Description:
Some times, it’s very rare to happen, BUT sometimes ROBLOX crashes when you click attach (maybe cause I have a potato pc)

Describe how to fully reproduce the issue:
I’m not really sure how it crashes, seems to do it randomly.

Other Details:
Idk if you know about this...
Maybe you do maybe you don’t.
Who knows.

**Comment by 3dsboy08** [comment]
yeah working on that, I cant reproduce it effectively though so it might take a while
