### ISSUE TITLE
Not Injecting.

### ISSUE THREAD

**Issue by PitchBlackTerrorT** [3dsboy08/Synapse-Issues#53]
Sometimes when i inject it dosent inject like, i play tower battles and inject it in the round. it does work, but when its over and the other round is starting im in and inject and it always says authenicating.

**Comment by PitchBlackTerrorT** [comment]
mhm :/

**Comment by carmelpr12** [comment]
failing to inject on Apocalypse Rising it worked fine for like 20mins and now it doesn't work

**Comment by PitchBlackTerrorT** [comment]
Okay, i know how to do it a little. So thx for your responding!
