### ISSUE TITLE
Ani-hack not letting dex or anything execute 

### ISSUE THREAD

**Issue by DexNom** [3dsboy08/Synapse-Issues#60]
https://www.roblox.com/games/1515242024/Sword-Fighting-Simulator# It a tight ant-hack I can’t execute anything

**Comment by Direnta** [comment]
Holy crap, you're right.
I just injected Synapse and it instantly kicks.
![image](https://user-images.githubusercontent.com/33453589/37559799-6c662272-2a02-11e8-86cb-ea0daae3a5ef.png)

**Comment by radiantmod** [comment]
no it doesnt
it only does that if a script errors

**Comment by 3dsboy08** [comment]
nobody plays this game, waste of my time
