### ISSUE TITLE
CB:R

### ISSUE THREAD

**Issue by himyfriendmynameisjeff** [3dsboy08/Synapse-Issues#61]
I don't know if this is still present, but before when you attached synapse to cb:r it crashed your game.

**Comment by BinaraKing** [comment]
That was RAC if I recall correctly. I'm pretty sure 3ds also added a RAC bypass which should fix the crash. Test again lad, if it works, post here and 3ds will probably close the issue. If not, then he'll probably look into it himself.

**Comment by himyfriendmynameisjeff** [comment]
It works, you may close this thread 3ds. sorry.

**Comment by 3dsboy08** [comment]
My RAC bypass is only enabled on CB:RO, not CB:R @BinaraKing. I did not test it on there.
