### ISSUE TITLE
decompiler protection on city-17 for certain scripts

### ISSUE THREAD

**Issue by checkraisefold** [3dsboy08/Synapse-Issues#62]
trying to decompile a localscript in their rarespinmenu gui thingy crashes roblox
`Synapse:CopyString(Synapse:Decompile(game.Players.LocalPlayer.PlayerGui.UIs.RareSpinMenu.LocalScript)`
decompiling other scripts works fine, also attaching sometimes clears playergui (why)

https://www.roblox.com/games/509062192/City-17-City-RP

**Comment by 3dsboy08** [comment]
this is an issue with unluac, not Synapse. not much I can do to fix it unfortunately.

**Comment by checkraisefold** [comment]
i see, yeah it's been done before. (selenium broke unluac and nobody got its source yet lold)
