### ISSUE TITLE
synapse 'surviving teleports' worked for one update

### ISSUE THREAD

**Issue by checkraisefold** [3dsboy08/Synapse-Issues#67]
mysteriously it isn't working for 99% of people

**Comment by Direnta** [comment]
works for me idk your problem lmao 😆

**Comment by checkraisefold** [comment]
try teleporting to a place using
game:GetService("TeleportService"):Teleport(id)
then running scripts after
it literally doesn't work for me and other people
@Direnta

**Comment by 3dsboy08** [comment]
test

**Comment by checkraisefold** [comment]
what @3dsboy08
