### ISSUE TITLE
Synapse Decompiler returning the same Source on any script in any game.

### ISSUE THREAD

**Issue by iCookieBG** [3dsboy08/Synapse-Issues#77]
UPDATE: DECOMPILER RETURNS THE SAME THING ON ANY LCLOSURE AND/OR SCRIPT

Issue Name: Problem decompiling Local/ModuleScripts

Issue Description: When I try to decompile any running LocalScript, I get the same Source every time, even if the script is blank. I get this issue in **every** game I join and any script I try to decompile. Here's the source I get: https://pastebin.com/dcWwaHHR. Also this doesn't challenge any other problems, it acts as a normal script and I can still get the upvalues and enviorment of it. I tried re-downloading and restarting my PC, even downloading the new Java Update, but none of it helped.

Describe how to fully reproduce the issue: Go on any game and try decompiling any Local/ModuleScript, including the default PlayerScripts.

Other details: The first time I got this was when I was trying to decompile the main script in Jailbreak. I made a quick script that compares 2 completely different scripts' sources.
`local a = decompile(game:GetService'Players'.LocalPlayer.PlayerScripts.LocalScript)
local b = decompile(game:GetService'Players'.LocalPlayer.PlayerScripts.BubbleChat)
print(a == b) --> printed true`

**Comment by juniorjacob** [comment]
He'll likely find a way to get the format code working but for now just get https://atom.io/ and paste it in there works the same way

**Comment by 3dsboy08** [comment]
reinstall roblox
