### ISSUE TITLE
Misspelling in Error Box

### ISSUE THREAD

**Issue by juniorjacob** [3dsboy08/Synapse-Issues#78]
Issue Name: Misspelling in Synapse Error Box

Issue Description: There's a misspelling in an error box that pops up when the Synapse client cannot get the required data from ROBLOX correctly.

To reproduce make the data from ROBLOX unusable and look at the box that it posts unless of course, you can just spawn the box yourself.

Other Details: http://prntscr.com/joo9s8

**Comment by 3dsboy08** [comment]
fixed lol
