### ISSUE TITLE
getsenv()/getmenv() Issue

### ISSUE THREAD

**Issue by juniorjacob** [3dsboy08/Synapse-Issues#79]
**Issue Name**: GetSenv() / GetMenv() Not Getting Script Locals, Functions, and Tables

**Issue Description**: I'll try and use the functions to grab locals and functions to use for a script and they won't return anything, they do return a table but the table is completely empty. Tested other Get's like GetRenv() and they work fine. I decompiled both scripts I tested on both weren't empty.

**Describe how to fully reproduce the issue**: Try to use purely getsenv() on a clientscript or a module script to get the values inside each.

**Other Details**: If there's a required install for getsenv() support that you don't have posted publicly please put it somewhere to access, and if you do already have a download link for its support I would like that to get support for the function.

**Comment by 3dsboy08** [comment]
getsenv gets the scripts enviorment, if you want locals/upvalues use debug.getupvalues
