### ISSUE TITLE
Synapse keeps opening this 'Synapse Output window' or something like that.

### ISSUE THREAD

**Issue by ehsaan555** [3dsboy08/Synapse-Issues#8]
Hi! I inject Synapse (which is fine) and *most* scripts will open this Output Console let me just get you a screenshot. (thx) 
http://prntscr.com/gi9sz2
I tried this on a Rocky2u script AND a simple Fire Remote Script. 
%.% People said they didn't have this error, you got anything 3ds, or is this just for me?

**ROBLOX have patched ALOT from Synapse recently.

**Comment by 3dsboy08** [comment]
This is Adonis, not ROBLOX.

**Comment by ehsaan555** [comment]
@3dsboy08 This was on Arc of The Elements too though. They don't use adonis, right? e.e

**Comment by 3dsboy08** [comment]
They do.
