### ISSUE TITLE
Add 4k Support.

### ISSUE THREAD

**Issue by Jak16** [3dsboy08/Synapse-Issues#9]
Discord Id:
Jak16#5737

Report Type (script issue/etc):
Screen Resolution

Report Content: 
Synapse is really hard to use in 4k resolution, I can't go any lower than 4k as I am on a 40" TV and everything will look like crap. I cannot use the scroll bars to scroll up, down, left or right and all the buttons are half eaten by the void. 

Images/other details: 
Here is an image http://prntscr.com/giw2in

**Comment by Backtalk3rs** [comment]
The image only shows the buttons are only improperly sized, maybe try to show the 4K resolution TV?

**Comment by 3dsboy08** [comment]
This is caused by your font/accessibility settings being screwed up, not 4K.
